### ISSUE TITLE
 microservices-annotator.toml support

### ISSUE THREAD

**Issue by linux-china** [strangeway-org/microservices-annotator-db#1]
Lots of Java developer likes to use interface to proxy remote request, for example: 

```java
interface UserService {
    User findUserById(Integer id);
}
```

UserService interface will be proxied to remote call, and it should be marked as REQUEST, STREAMING or other types. 

Is it possible to load  microservices-annotator.toml  from project root directory and annotate these API call? 

```toml
[[STREAMING]]
name = "RSocket Stream"
methods = ["io.rsocket.RSocket.requestStream"]

[[REQUEST]]
name = "RSocket"
classes = ["io.rsocket.RSocket", "org.springframework.messaging.rsocket.RSocketRequester"]
```

If possible, could the plugin  try to find META-INF/microservices-annotator.toml in the jars?
